### ISSUE TITLE
migrate applications to components

### ISSUE THREAD

**Issue by bf-monster** [betfinio/app#165]

**Comment by bf-monster** [comment]
@bf-san :
- [ ] statistics
- [ ] staking
- [ ] roulette

@bf-plane :
- [ ] luro
- [ ] predict
- [ ] stones

@bf-monster : 
- [ ] template
- [ ] academy
- [ ] games


- [ ] elections ???

**Comment by bf-monster** [comment]
step:
1. bun add @betfinio/components
2. replace all imports from betfinio_app/* to @betfinio/components/{ui,shared,hooks}
3. fix colors: primary => background, yellow-400 => primary...... 
4. replace clsx's cx with @betfinio/components/lib 'cn'
5. replace old divs with new buttons and other components from new library
6. clear tailwind - must be empty or repo's variables only, consult with me on this

**Comment by bf-san** [comment]
8.In order to use in the repository tailwind.config.js of the components library. You need to add it as a preset in the consuming repo.
it will look like so:
![Image](https://github.com/user-attachments/assets/3625979a-69f2-4923-ae0b-249cb0b4c501)
9.Additionally you need to add @betfinio/components in your bootstrap.tsx file
![Image](https://github.com/user-attachments/assets/af851c6c-c8e7-4eee-aeff-5ae9e795ef39)
